Repository Gamez0/lemonade-tycoon, pull requests merged in 2025-03, with the labels that each got.

#18 [BugFix] Warning AnimationManager key already exists
  src/scenes/day-scene.ts
Labels: bug

#19 [Feature] Add money icon
  src/scenes/day-scene.ts
  src/scenes/preparation-scene.ts
  src/ui/budget-container.ts
Labels: enhancement

#21 [Bug] Lemonade is made when supply is not enough
  src/scenes/day-scene.ts
Labels: bug

#28 [Feature] Random number should be added when customer checks the price
  src/scenes/day-scene.ts
Labels: enhancement

#31 [Feature] Show today's setting on day-scene.ts
  src/models/location.ts
  src/scenes/day-scene.ts
  src/ui/today-setting-container.ts
Labels: enhancement

#36 [Feature] Cost per cups
  src/models/recipe.ts
  src/models/supplies.ts
  src/ui/game-control-container.ts
  src/ui/recipe-container.ts
Labels: enhancement

#40 [Docs] PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#42 [Enhancement] Install eslint
  eslint.config.mjs
  package.json
  yarn.lock
Labels: enhancement

#44 [GitHub] Adding Feature categorization in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: github

#46 Fixed issue #33
  src/ui/map-container.ts
Labels: bug

#49 [Docs] Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#5 [Feature] More Realistic Temperature
  src/scenes/preparation-scene.ts
  src/types/weather-forecast.ts
  src/ui/weather-news-container.ts
Labels: enhancement, good first issue

#7 [UI/UX] Move Minus Icon #6
  src/ui/buy-supplies-container.ts
  src/ui/item-purchase-container.ts
Labels: enhancement

#51 [Docs]: Update README.md
  README.md
  public/assets/lemonade-tycoon-thumbnail-black.png
  screenshot.png
Labels: documentation

#53 [Feature] Add main menu
  public/assets/logo.png
  src/main.ts
  src/scenes/MainMenu.ts
Labels: enhancement

#56 [Feature] Check player has enough money to rent the location
  src/models/location.ts
  src/scenes/preparation-scene.ts
Labels: enhancement
